<?php

    return array(

        'desde' => [
            '0'=>'Hoy',
            '1'=>'Ayer',
            '2'=>'Hace una semana',
            '3'=>'Hace 15 Días',
            '4'=>'Hace un mes'
        ],
        'sueldo' =>[
            '0' => 'Menos de $6,000',
            '1' => '$6,000 - $8,000',
            '2' => '$8,000 - $12,000',
            '3' => '$12,000 - $16,000',
            '4' => '$16,000 - $20,000',
            '5' => '$20,000 - $25,000',
            '6' => 'Más de $25,000',
        ],
        'month' => [
            '01' 		=> 'Enero',
            '02' 		=> 'Febrero',
            '03' 		=> 'Marzo',
            '04'		=> 'Abril',
            '05' 		=> 'Mayo',
            '06' 		=> 'Junio',
            '07' 		=> 'Julio',
            '08' 		=> 'Agosto',
            '09'		=> 'Septiembre',
            '10'  		=> 'Octubre',
            '11' 		=> 'Noviembre',
            '12' 		=> 'Diciembre'
        ],
        'date' => [
            '01' 		=> '01',
            '02' 		=> '02',
            '03' 		=> '03',
            '04'		=> '04',
            '05' 		=> '05',
            '06' 		=> '06',
            '07' 		=> '07',
            '08' 		=> '08',
            '09'		=> '09',
            '10'  		=> '10',
            '11' 		=> '11',
            '12' 		=> '12',
            '13' 		=> '13',
            '14' 		=> '14',
            '15' 		=> '15',
            '16' 		=> '16',
            '17' 		=> '17',
            '18' 		=> '18',
            '19' 		=> '19',
            '20' 		=> '20',
            '21' 		=> '21',
            '22' 		=> '22',
            '23' 		=> '23',
            '24' 		=> '24',
            '25' 		=> '25',
            '26' 		=> '26',
            '27' 		=> '27',
            '28' 		=> '28',
            '29' 		=> '29',
            '30' 		=> '30',
            '31' 		=> '31',
        ],
        
        'pais' => [
            'Mexico' 		=> 'Mexico',
        ],
        'state' => [
            'ags' 		=> 'Aguascalientes',
            'BC'                => 'Baja California',
            'BCS'               => 'Baja California Sur',
            'Camp'              => 'Campeche',
            'Coah'              => 'Coahuila de Zaragoza',
            'Col'               => 'Colima',
            'Chis'              => 'Chiapas',
            'Chih'              => 'Chihuahua',
            'DF'                => 'Distrito Federal',
            'Dgo'               => 'Durango',
            'Gto'               => 'Guanajuato',
            'Hgo'               => 'Hidalgo',
            'Jal'               => 'Jalisco',
            'Mex'               => 'Mexico',
            'Mich'              => 'Michoacan de Ocampo',
            'Mor'               => 'Morelos',
            'Nay'               => 'Nayarit',
            'NL'               => 'Nuevo Leon',
            'Oax'              => 'Oaxaca',
            'Pue'              => 'Puebla',
            'Qro'              => 'Queretaro',
            'Q.Roo'            => 'Quintana Roo',
            'SLP'              => 'San Luis Potosí',
            'Sin'              => 'Sinaloa',
            'Son'           => 'Sonora',
            'Tab'              => 'Tabasco',
            'Tamps'            => 'Tamaulipas',
            'Tlax'             => 'Tlaxcala',
            'Ver'              => 'Veracruz de Ignacion de la LLave',
            'Yuc'              => 'Yucatan',
            'Zac'              => 'Zacatecas',
        ],
        
         'mpio' => [
            'Chih' 		=> 'Ahumada',
             'Chih' 		=> 'Juarez',
             'ags' 		=> 'Asientos',
        ],
    );